Nick rec index table
ucsb-cs156-f22/team03-f22-5pm-3 pull request #51
Opened 2022-11-11 01:26 UTC by nick-pellegrin

closes #15

2022-11-11 02:15 UTC, josiahnross approved these changes
LGTM!

2022-11-12 00:46 UTC, Gopu2001 requested changes
Hey Nick, overall good progress. One nitpick, otherwise there are some issues with the endpoint of the API you are calling. May you please fix them? Thanks!

2022-11-12 00:46 UTC, Gopu2001 commented on frontend/src/main/pages/Recommendations/RecommendationsIndexPage.js
> +            { method: "GET", url: "/api/recommendations/all" },
You should change this URL. When I test your branch, I get some errors in API requests. According to your Recommendation controller java file, the endpoint is defined as: `/api/Recommendation/all`
```suggestion
            { method: "GET", url: "/api/Recommendation/all" },
```

2022-11-12 00:46 UTC, Gopu2001 commented on frontend/src/main/pages/Recommendations/RecommendationsIndexPage.js
> +      ["/api/recommendations/all"],
Incorrect endpoint:
```suggestion
      ["/api/Recommendation/all"],
```

2022-11-12 00:46 UTC, Gopu2001 commented on frontend/src/tests/components/Recommendations/RecommendationsTable.test.js
> +    // expect(deleteButton).toHaveClass("btn-danger");
Nitpick: commented code should only be for documentation purposes. Though I understand if you want to keep this in for the later PR.

2022-11-12 00:46 UTC, Gopu2001 commented on frontend/src/tests/pages/Recommendations/RecommendationsIndexPage.test.js
> +        axiosMock.onGet("/api/recommendations/all").reply(200, recommendationsFixtures.threeRecommendations);
bad endpoint:
```suggestion
        axiosMock.onGet("/api/Recommendation/all").reply(200, recommendationsFixtures.threeRecommendations);
```

2022-11-12 00:46 UTC, Gopu2001 commented on frontend/src/tests/pages/Recommendations/RecommendationsIndexPage.test.js
> +        axiosMock.onGet("/api/recommendations/all").reply(200, recommendationsFixtures.threeRecommendations);
bad endpoint:
```suggestion
        axiosMock.onGet("/api/Recommendation/all").reply(200, recommendationsFixtures.threeRecommendations);
```

2022-11-12 00:46 UTC, Gopu2001 commented on frontend/src/tests/pages/Recommendations/RecommendationsIndexPage.test.js
> +        axiosMock.onGet("/api/recommendations/all").timeout();
bad endpoint:
```suggestion
        axiosMock.onGet("/api/Recommendation/all").timeout();
```

2022-11-12 21:03 UTC, Gopu2001 approved these changes
Nice, everything works now!

2022-11-12 22:19 UTC, merged